# Generated by Django 3.2 on 2021-05-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20210505_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='tagging_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence_text',
            field=models.TextField(null=True),
        ),
    ]
